databases:
  - name: sample_django
    databaseName: sample_django
    user: user
    region: singapore
    plan: free

services:
  - type: web
    name: rest_api
    runtime: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn server.wsgi:application --timeout 600"
    autoDeploy: true
version: "1"