databases:
  - name: sample_django
    databaseName: sample_django
    user: user
    region: singapore
    plan: free

services:
  - type: web
    name: rest_api
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn server.wsgi:apprication --timeout 600"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample_django
          property: connectionString
      - key: DATABASE1_URL
        fromDatabase:
          name: sample_django
          property: connectionString
      - key: SECRET_KEY
        generateValue: true


    autoDeploy: true
